name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8

    - name: Run Tests with JDK 8
      run: mvn test

    - name: Setup Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Run Tests With JDK 11
      run: mvn test

    - name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 17

    - name: Run Tests With JDK 17
      run: mvn test
